### PR TITLE
Fix Decoder forward(..., length) 

### PR DESCRIPTION
**Pull request by faroit**
Addresses #7

* [X] adding unit tests for multichannel inputs
* [x] fix length arguments apply

### CODE REVIEW

**Comment by faroit** [comment]
@mpariente `torch.stft` doesn't support 2D, `asteroid` doesn't support 3D inputs, any idea for a less hacky unit test?

**Comment by mpariente** [comment]
Did torch.stft always behave like this?

**Comment by mpariente** [comment]
Actually, we want to behave like nn.Conv1d, not like torch.stft, so it doesn't matter to me that the shapes are not the same.

**Comment by faroit** [comment]
> Actually, we want to behave like nn.Conv1d, not like torch.stft, so it doesn't matter that the shapes are not the same. 

maybe then we add the channel-> batch wrapping for `torch.stft` so that they give the same output?

**Comment by faroit** [comment]
@mpariente maybe you are quicker to carry out the unit-test changes? In that case I can just revert 18068e2 so that we just merge the fix followed by unit test changes by you later

**Comment by mpariente** [comment]
I'd rather have the unit test before merging and sorry but I don't have time for it now.

**Comment by faroit** [comment]
@jonashaag do you know of any news regarding nd-support for torch.stft and torch.istft? 

I think you were reporting this first on https://github.com/pytorch/pytorch/issues/42813

**Comment by faroit** [comment]
> I'd rather have the unit test before merging and sorry but I don't have time for it now.

@mpariente I added a wrapper. The relevant tests pass but I now get

```
       except RuntimeError:
            # If there was a RuntimeError, the OLA had zeros. So we cannot unit test
            # But we can make sure that istft raises a warning about it.
            with pytest.warns(RuntimeWarning):
>               _ = istft(spec_asteroid, length=output_len)
E               Failed: DID NOT WARN. No warnings of type (<class 'RuntimeWarning'>,) was emitted. The list of emitted warnings is: [].
```

any idea?

**Comment by faroit** [comment]
@mpariente ready for review

**Review by mpariente — APPROVED** [review]
Great, thanks !

**Comment by jonashaag** [comment]
@faroit haven't read this issue and I'm not following the PyTorch one. Feel free to follow up there with whatever you think is appropriate. I can't reopen that ticket

**Comment by faroit** [comment]
@mpariente 👍 would you pushing a new release soon?

**Pull request merged**
